services:
  postgres:
    image: postgres:latest
    container_name: dbt_postgres
    environment:
      POSTGRES_USER: ${DBT_USER}
      POSTGRES_PASSWORD: ${DBT_PASSWORD}
      POSTGRES_DB: dbt_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DBT_USER} -d dbt_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: